export default {
  agencies: [
    {
      location: {
        geolocation: {
          latitude: -20.2158721,
          longitude: -70.1476853,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "Sargento aldea",
        street_number: "776",
      },
      status: "active",
      agency_id: "3167",
      agency_name: "Punto Blue Express Good Travel",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "08:30-18:30",
        tuesday: "08:30-18:30",
        wednesday: "08:30-18:30",
        thursday: "08:30-18:30",
        friday: "08:30-18:30",
        saturday: "10:00-13:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.3739217,
          longitude: -69.64986,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "POZO ALMONTE",
        city_id: "1401",
        street_name: "Predio Santa Ana Manzana (Diez y seis de julio)",
        street_number: "3",
        other_info: "Antes de la mezquita camino a la huayca",
      },
      status: "active",
      agency_id: "4043",
      agency_name: "Punto Blue Express El Emporio De Lorenzo",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "08:00-18:00",
        tuesday: "08:00-18:00",
        wednesday: "08:00-18:00",
        thursday: "08:00-18:00",
        friday: "08:00-18:00",
        saturday: "08:00-18:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "8:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.215786,
          longitude: -70.148148,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "Vivar",
        street_number: "786",
        other_info: "local 1",
      },
      status: "active",
      agency_id: "8584",
      agency_name: "Punto Blue Express Universo",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "10:00-20:30",
        tuesday: "10:00-20:30",
        wednesday: "10:00-20:30",
        thursday: "10:00-20:30",
        friday: "10:00-20:30",
        saturday: "10:00-20:30",
        sunday: "10:00-20:30",
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.216344,
          longitude: -70.1561679,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "Freddy Taberna",
        street_number: "59",
        other_info: "(Esquina con Arturo Prat Chacón)",
      },
      status: "active",
      agency_id: "5608",
      agency_name: "Punto Blue Express Gimnasio Pacific IQUIQUE",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "07:00-21:00",
        tuesday: "07:00-21:00",
        wednesday: "07:00-21:00",
        thursday: "07:00-21:00",
        friday: "07:00-21:00",
        saturday: "07:00-17:00",
        sunday: null,
      },
      cut_hours: {
        monday: "11:00",
        tuesday: "11:00",
        wednesday: "11:00",
        thursday: "11:00",
        friday: "11:00",
        saturday: "11:00",
        sunday: null,
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.2238111,
          longitude: -70.1409383,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "Manuel Rodriguez",
        street_number: "1593",
      },
      status: "active",
      agency_id: "1302",
      agency_name: "Punto Blue Express Ñu Store",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "08:00-16:00",
        tuesday: "08:00-16:00",
        wednesday: "08:00-16:00",
        thursday: "08:00-16:00",
        friday: "08:00-16:00",
        saturday: "09:00-14:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.247541,
          longitude: -70.129175,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "cerró dragón",
        street_number: "3182",
      },
      status: "active",
      agency_id: "6760",
      agency_name: "Punto Blue Express Ineko Card Shop",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "15:30-22:00",
        tuesday: "15:30-22:00",
        wednesday: "15:30-22:00",
        thursday: "15:30-22:00",
        friday: "15:30-22:00",
        saturday: "17:00-22:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.269162,
          longitude: -70.1077989,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "ALTO HOSPICIO",
        city_id: "1107",
        street_name: "Av los condores",
        street_number: "3046",
      },
      status: "active",
      agency_id: "5304",
      agency_name: "Punto Blue Express  Nutrifit",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "10:30-18:00",
        tuesday: "10:30-18:00",
        wednesday: "10:30-18:00",
        thursday: "10:30-18:00",
        friday: "10:30-18:00",
        saturday: null,
        sunday: null,
      },
      cut_hours: {
        monday: "14:00",
        tuesday: "14:00",
        wednesday: "14:00",
        thursday: "14:00",
        friday: "14:00",
        saturday: "14:00",
        sunday: "14:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.2778126,
          longitude: -70.0800049,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "ALTO HOSPICIO",
        city_id: "1107",
        street_name: "Calle Ovalle",
        street_number: "4560",
      },
      status: "active",
      agency_id: "5666",
      agency_name: "Punto Blue Express Sólo dilo con globos",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "10:00-20:00",
        tuesday: "10:00-20:00",
        wednesday: "10:00-20:00",
        thursday: "10:00-20:00",
        friday: "10:00-20:00",
        saturday: "10:00-18:00",
        sunday: "10:00-15:00",
      },
      cut_hours: {
        monday: "10:00",
        tuesday: "10:00",
        wednesday: "10:00",
        thursday: "10:00",
        friday: "10:00",
        saturday: "10:00",
        sunday: "10:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.2517897,
          longitude: -70.1260407,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "IQUIQUE",
        city_id: "1101",
        street_name: "Los Algarrobos",
        street_number: "3407",
      },
      status: "active",
      agency_id: "4452",
      agency_name: "Punto Blue Express  La Dominicana Bazar",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "07:00-21:00",
        tuesday: "07:00-21:00",
        wednesday: "07:00-21:00",
        thursday: "07:00-21:00",
        friday: "07:00-21:00",
        saturday: "07:00-21:00",
        sunday: "10:00-21:00",
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.4882914,
          longitude: -69.3297356,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "PICA",
        city_id: "1405",
        street_name: "Sebastian Ugariza",
        street_number: "784",
      },
      status: "active",
      agency_id: "3622",
      agency_name: "Punto Blue Express  Sandymarket",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "08:00-22:00",
        tuesday: "08:00-22:00",
        wednesday: "08:00-22:00",
        thursday: "08:00-22:00",
        friday: "08:00-22:00",
        saturday: "08:00-22:00",
        sunday: "08:00-22:00",
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.2777925,
          longitude: -70.0982514,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "ALTO HOSPICIO",
        city_id: "1107",
        street_name: "Av. La Pampa",
        street_number: "3779",
        other_info: "Terminal Agropecuario Norte-Sur, Galpon4",
      },
      status: "active",
      agency_id: "6282",
      agency_name: "Punto Blue Express Kouzi",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: null,
        tuesday: "10:00-18:00",
        wednesday: "10:00-18:00",
        thursday: "10:00-18:00",
        friday: "10:00-18:00",
        saturday: "10:00-18:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -20.2702714,
          longitude: -70.1005889,
        },
        country_name: "Chile",
        state_name: "Tarapacá",
        city_name: "ALTO HOSPICIO",
        city_id: "1107",
        street_name: "Av. Ramón Pérez Opazo",
        street_number: "3218",
        other_info: "B",
      },
      status: "active",
      agency_id: "5444",
      agency_name: "Punto Blue Express Kouzi Alto Hospicio",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: null,
        tuesday: "10:00-18:00",
        wednesday: "10:00-18:00",
        thursday: "10:00-18:00",
        friday: "10:00-18:00",
        saturday: "10:00-18:00",
        sunday: "10:00-18:00",
      },
      cut_hours: {
        monday: null,
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -23.5842224,
          longitude: -70.3821355,
        },
        country_name: "Chile",
        state_name: "Antofagasta",
        city_name: "ANTOFAGASTA",
        city_id: "2101",
        street_name: "Ignacio Carrera Pinto 825",
        street_number: "825",
      },
      status: "active",
      agency_id: "4763",
      agency_name: "Punto Blue Express El Pato",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "13:00-21:00",
        tuesday: "13:00-21:00",
        wednesday: "13:00-21:00",
        thursday: "13:00-21:00",
        friday: "13:00-21:00",
        saturday: "13:00-21:00",
        sunday: "13:00-20:00",
      },
      cut_hours: {
        monday: "13:00",
        tuesday: "13:00",
        wednesday: "13:00",
        thursday: "13:00",
        friday: "13:00",
        saturday: "13:00",
        sunday: "13:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -23.3370894,
          longitude: -69.8455979,
        },
        country_name: "Chile",
        state_name: "Antofagasta",
        city_name: "SIERRA GORDA",
        city_id: "2103",
        street_name: "BARROS LUCO",
        street_number: "127",
        other_info: "BAQUEDANO - SIERRA GORDA",
      },
      status: "active",
      agency_id: "6720",
      agency_name: "Punto Blue Express Donde Los Abuelos",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "11:00-16:00",
        tuesday: "11:00-16:00",
        wednesday: "11:00-16:00",
        thursday: "11:00-16:00",
        friday: "11:00-16:00",
        saturday: "11:00-16:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "11:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
    {
      location: {
        geolocation: {
          latitude: -23.6492002,
          longitude: -70.3888092,
        },
        country_name: "Chile",
        state_name: "Antofagasta",
        city_name: "ANTOFAGASTA",
        city_id: "2101",
        street_name: "Av Andres Sabella",
        street_number: "3092",
      },
      status: "active",
      agency_id: "3456",
      agency_name: "Punto Blue Express Comerciairba",
      package_reception: true,
      pickup_availability: true,
      open_hours: {
        monday: "09:00-18:30",
        tuesday: "09:00-18:30",
        wednesday: "09:00-18:30",
        thursday: "09:00-18:30",
        friday: "09:00-18:30",
        saturday: "09:00-13:00",
        sunday: null,
      },
      cut_hours: {
        monday: "12:00",
        tuesday: "12:00",
        wednesday: "12:00",
        thursday: "12:00",
        friday: "12:00",
        saturday: "12:00",
        sunday: "12:00",
      },
      lunch_hours: {
        monday: null,
        tuesday: null,
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null,
      },
      last_updated: "",
      volumetric_capacity: 0,
      maximum_package_dimensions: {
        length: 100,
        height: 100,
        width: 100,
        weight: 20,
      },
    },
  ],
};
